REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00057621','COL0005762','Construcción sostenible y resiliencia de la infraestructura al cambio y variabilidad climática');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00057622','COL0005762','Diseńo de política y planeación energética');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00057623','COL0005762','Eficiencia Energética');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00057624','COL0005762','Evolucion del Sector Electrico Colombiano');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00057625','COL0005762','Fuentes no convencionales de energía');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00057626','COL0005762','Gestión Energética');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00057627','COL0005762','Mitigación y adaptación al cambio climático');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00057628','COL0005762','Vigilancia tecnológica y prospectiva en equipos de uso final de la energía');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00108891','COL0010889','Alimentos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00108892','COL0010889','Ambiental');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00108893','COL0010889','Biomasa y Biocombustibles');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00108894','COL0010889','Biotecnologia y Bioprocesos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00108895','COL0010889','Catálisis y Procesos Catalíticos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00108896','COL0010889','Educación');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00108897','COL0010889','Especialidades Químicas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00108898','COL0010889','Gestión');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00108899','COL0010889','Materiales');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL001088910','COL0010889','Modelamiento y Simulación');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL001088911','COL0010889','Nuevas Tecnologías');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL001088912','COL0010889','Oleoquímica');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL001088913','COL0010889','Polímeros y Procesos de Polimerización');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00008821','COL0000882','Calidad toxicológica y microbiológica de aguas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00008822','COL0000882','Contaminantes emergentes');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00008823','COL0000882','Destino ambiental de contaminantes');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00008824','COL0000882','Potabilización de aguas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00008825','COL0000882','Tratamiento y re-uso de aguas residuales');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00211391','COL0021139','Automatización de máquinas - robots procesos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00211392','COL0021139','Diseńo de productos y procesos industriales y preseries');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00211393','COL0021139','Manufactura Flexible');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00211394','COL0021139','Prototipado rápido y materiales en gradiente');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00211395','COL0021139','Realidad y Manufactura Virtual');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00211396','COL0021139','Repotenciación tecnológica de equipos y procesos industriales');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00105661','COL0010566','Análisis de tendencias Escaneo, vigilancia y monitoreo y Estudios de Futuros');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00105662','COL0010566','Biociencias y Gestión');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00105663','COL0010566','Direccionamiento Estratégico e Inteligencia Tecnológica y organizacional');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00105664','COL0010566','Gerencia Estratégica Ambiental');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00105665','COL0010566','Gerencia de proyectos y fortalecimiento Institucional');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00105666','COL0010566','Gestión Tecnológica');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00105667','COL0010566','Gestión de la Ciencia, tecnología e Innovación');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00105668','COL0010566','Productividad y Competitividad');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00290851','COL0029085','INTEGRIDAD DE EQUIPOS E INSTALACIONES MECÁNICAS');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00290852','COL0029085','MECANISMOS DE FALLA DE ELEMENTOS MECÁNICOS');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00290853','COL0029085','NUEVOS MATERIALES');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00290854','COL0029085','TRATAMIENTOS SUPERFICIALES');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00290855','COL0029085','TRATAMIENTOS TÉRMICOS DE MATERIALES');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00244991','COL0024499','Desarrollo de Productos Industriales Metalmecánicos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00244992','COL0024499','Diseńo de Bienes de Capital para MIPYMES');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00244993','COL0024499','Máquinas y dispositivos de rehabilitación');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00244994','COL0024499','Robotica');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00077581','COL0007758','Electrónica de potencia');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00077582','COL0007758','Fuentes alternativas de energía');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00077583','COL0007758','Inteligencia Computacional');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00077584','COL0007758','Modelamiento y Control de Sistemas de Alta Tensión');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00077585','COL0007758','Modelamiento, Simulación y Control de Sistemas Dinámicos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00077586','COL0007758','Métodos formales para diseńo de controladores de sistemas dinámicos a eventos discretos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00077587','COL0007758','Procesamiento de Seńales');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00077588','COL0007758','Visión Artificial');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00321511','COL0032151','COMUNICACIÓN DE LA SALUD');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00321512','COL0032151','GESTIÓN INTEGRAL DURABLE');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00321513','COL0032151','GESTIÓN INTEGRAL EN LAS ORGANIZACIONES DEL SECTOR SALUD');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00321514','COL0032151','INGENIERIA CLINICA, GESTION Y EVALUACIÓN DE TECNOLOGIAS EN SALUD');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00224311','COL0022431','Automatización de Máquinas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00224312','COL0022431','Robótica Industrial');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00224313','COL0022431','Robótica móvil');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00392791','COL0039279','Calidad del aire y salud');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00392792','COL0039279','Caracterización de la contaminación');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00392793','COL0039279','Desarrollo de instrumentación atmosférica avanzada');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00392794','COL0039279','Fuentes y sumideros de gases de efecto invernadero');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00392795','COL0039279','Modelación de la calidad del aire');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00392796','COL0039279','Nuevas tecnologías y diseńos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00392797','COL0039279','Química atmosférica');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00440361','COL0044036','Innovación Industrial');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00440362','COL0044036','Organizaciones, medio ambiente y eco-competitividad');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00440363','COL0044036','Productividad, calidad y competitividad');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00440364','COL0044036','Redes empresariales');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00440365','COL0044036','Responsabilidad empresarial por diseńo');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00462641','COL0046264','Diseńo de productos, procesos y equipos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00462642','COL0046264','Gestión tecnología en agroindustria');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00462643','COL0046264','Prospectiva tecnológica agroindustrial');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00503471','COL0050347','Biomecánica computacional');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00503472','COL0050347','Biotecnología');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00503473','COL0050347','Dinámica de fluidos computacional');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00503474','COL0050347','Elementos Finitos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00503475','COL0050347','Elementos sin malla');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00503476','COL0050347','Investigación en Ciencias de la Salud');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00503477','COL0050347','Modelado de Materiales y fenómenos físicos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00503478','COL0050347','Métodos Numéricos en Ingeniería');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00503479','COL0050347','Simulación y Modelamiento en procesos térmicos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL005034710','COL0050347','Visualización Biomédica');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00555681','COL0055568','Disminución de emisiones atmosféricas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00555682','COL0055568','Optimización térmica de procesos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00555683','COL0055568','Secado');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00555684','COL0055568','Transformación Termoquímica de Biomasa');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00582651','COL0058265','Big Data');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00582652','COL0058265','Inteligencia de Negocios');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00582653','COL0058265','Mineria de Texto');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00582654','COL0058265','Minería de Datos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00582655','COL0058265','Minería de Datos Educativa');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00582656','COL0058265','Recuperación de Información');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00664541','COL0066454','Modelamiento y Simulación de procesos biofísicos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00664542','COL0066454','Modelamiento y simulación de estructuras granulares');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00664543','COL0066454','Modelamiento y simulación de plasmas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00664544','COL0066454','Modelamiento y simulación de propiedades magnéticas de nanoestructuras');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00664545','COL0066454','Modelamiento y simulación de propiedades mecánicas y tribológicas de materiales');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00664546','COL0066454','Optimización de procesos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00664547','COL0066454','Procesamiento digital de imágenes y de seńales');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00708961','COL0070896','ESTUDIOS SOCIOECONOMICOS URBANOS');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00708962','COL0070896','GESTION DE LA CADENA DE ABASTECIMIENTO. LOGISTICA');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00708963','COL0070896','PRODUCTIVIDAD Y CALIDAD EN LAS PYMES');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00495331','COL0049533','Biología celular y molecular de parásitos y hospederos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00495332','COL0049533','Control de sistemas interconectados complejos en biología y medicina');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00495333','COL0049533','Control y optimización de sistemas biológicos para producción industrial');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00495334','COL0049533','Desarrollo y aplicación de modelos matemáticos en epidemiología');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00495335','COL0049533','Herramientas diagnósticas para enfermedades parasitarias');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00495336','COL0049533','Herramientas terapéuticas para enfermedades parasitarias');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00495337','COL0049533','Simulación del Sistema Inmune de vertebrados y su interacción con patógenos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00659671','COL0065967','Aplicación de métodos geofísicos en ingeniería civil');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00659672','COL0065967','Estructuras multicapas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00659673','COL0065967','Investigación Básica en Arcillas Blandas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00659674','COL0065967','Investigación Básica en Suelos Parcialmente Saturados');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00659675','COL0065967','Investigación Básica en Suelos Residuales');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00837491','COL0083749','Catalisis Ambiental');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00837492','COL0083749','Degradación y mineralización de contaminantes');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00837493','COL0083749','Materiales avanzados a partir de minerales');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00837494','COL0083749','Nanomateriales para aplicaciones industriales');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00837495','COL0083749','Nanomateriales para energía');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00750321','COL0075032','Control de Procesos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00750322','COL0075032','Desarrollo de herramientas para enseńanza de la Ingeniería Química');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00750323','COL0075032','Intensificación de Procesos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00750324','COL0075032','Modelamiento de Procesos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00750325','COL0075032','Optimización de Procesos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00750326','COL0075032','Simulación de Procesos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00598521','COL0059852','Arquitectura empresarial, BPM y SOA');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00598522','COL0059852','Calidad y Pruebas de Software');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00598523','COL0059852','Capacitación en Tecnologías de la Información y la Comunicación - TIC y Web Social');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00598524','COL0059852','Evolución y Mantenimiento de Sistemas de Software');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00598525','COL0059852','Metodologías y Tecnologías para Desarrollo de Software');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00598526','COL0059852','Tecnologías Web/Wap');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00598527','COL0059852','Tendencias Curriculares en la Formación de Ingenieros de Software y de Sistemas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01051041','COL0105104','Desarrollo y adaptación industrial de nuevos procesos de manufactura');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01051042','COL0105104','Docencia en procesos de manufactura y materiales');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01051043','COL0105104','Investigación de Nuevos Materiales y sus procesos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01103091','COL0110309','Antenas y propagación');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01103092','COL0110309','Electromagnetismo computacional');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01103093','COL0110309','Identificación por Radio Frecuencia RFID');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01103094','COL0110309','Ingeniería de RF y microondas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01103095','COL0110309','Optoelectrónica y Telecomunicaciones Ópticas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01103096','COL0110309','Procesamiento de seńales en instrumentación, sensado remoto y comunicaciones inalámbricas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01103097','COL0110309','Seguridad Informática y Criptografía');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01103098','COL0110309','Sensado remoto, radar y sonar');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01103099','COL0110309','Simulación de sistemas biológicos para entrenamiento en áreas de Ciencias de la Salud');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL011030910','COL0110309','Telecomunicaciones por líneas de potencia');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01191371','COL0119137','DESARROLLO DE INSTRUMENTAL ASOCIADO A ANÁLISIS DE MATERIALES');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01191372','COL0119137','DESARROLLO Y CARACTERIZACIÓN DE NUEVOS MATERIALES PARA APLICACIONES ENERGÉTICAS');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01191373','COL0119137','INVESTIGACIÓN DE EFECTOS CORROSIVOS A ALTAS TEMPERATURAS EN AMBIENTES COMBUSTIBLES');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01191374','COL0119137','INVESTIGACIÓN DE MECANISMOS DE CORROSIÓN EN NUEVOS MATERIALES.');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01191375','COL0119137','INVESTIGACIÓN EN MECANISMOS DE DESGASTE Y FRICCIÓN POR ABRASIÓN, EROSIÓN, ADHESIÓN EN NUEVOS MATERIALES.');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01191376','COL0119137','INVESTIGACIÓN EN NUEVOS MATERIALES PARA APLICACIÓN EN LA INDUSTRIA PETROQUÍMICA');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01209791','COL0120979','Gestión Energética en Sistemas Eléctricos Industriales');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01209792','COL0120979','Modelado y control de sistemas de electrónica de potencia y maquinas eléctricas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01209793','COL0120979','Sistemas de Generación de Energía Renovable e integración Redes Inteligentes Smart Grid');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01488631','COL0148863','Apropiación del conocimiento');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01488632','COL0148863','Emprendimiento Tecnológico');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01488633','COL0148863','Gestión de la Innovación');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01488634','COL0148863','INTEGRACIÓN DE HERRAMIENTAS DE TECNOLOGÍAS DE INFORMACIÓN Y LAS COMUNICACIONES TIC EN EDUCACIÓN BÁSICA, MEDIA Y SUPERIOR');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01488635','COL0148863','Tecnologías de Información y las Comunicaciones');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01488636','COL0148863','Usabilidad y Diseńo Centrado en el Usuario');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00024391','COL0002439','CORROSIÓN, DEGRADACIÓN, PROTECCIÓN Y RECICLAJE DE MATERIALES');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00024392','COL0002439','Electroquímica Aplicada');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00024393','COL0002439','INGENIERÍA DE SUPERFICIES');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00024394','COL0002439','Ingenieria Molecular');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00228071','COL0022807','Desarrollo de Equipo de Prueba');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00228072','COL0022807','Eficiencia energética');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00228073','COL0022807','Iluminación');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00228074','COL0022807','Materiales Conductores');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00228075','COL0022807','Materiales Dieléctricos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00228076','COL0022807','Proteccion contra sobretensiones');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00228077','COL0022807','Seguridad Eléctrica');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00228078','COL0022807','Sistemas de puesta a tierra');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00144581','COL0014458','Calidad de la Energía Eléctrica');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00144582','COL0014458','Computación Flexible');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00144583','COL0014458','Desarrollo Tecnológico en sistemas de protección contra rayos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00144584','COL0014458','Descargas Eléctricas Atmosféricas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00144585','COL0014458','Generación Distribuida');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00144586','COL0014458','Mercados Energéticos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00144587','COL0014458','Operación de Sistemas Eléctricos de Potencia');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00144588','COL0014458','Sistemas de Protección de Sistemas Eléctricos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00144589','COL0014458','Sistemas de Puesta a Tierra');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL001445810','COL0014458','Smart Grids');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL001445811','COL0014458','Supervisión de Sistemas Eléctricos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL001445812','COL0014458','Tensiones Inducidas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00113851','COL0011385','Almacenamiento de Energía Eléctrica');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00113852','COL0011385','Cloud Computing');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00113853','COL0011385','Compatibilidad electrmagnética: antenas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00113854','COL0011385','Electrodos flotantes en el campo eléctrico');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00113855','COL0011385','Estudios de exposición de seres vivos.');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00113856','COL0011385','Estudios de rayos como fuente de interferencia electromagnética');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00113857','COL0011385','Evolución de redes eléctricas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00113858','COL0011385','Física de la descarga en gases');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00113859','COL0011385','Internet of Things IoT');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL001138510','COL0011385','Materiales Aislantes higroscópicos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL001138511','COL0011385','Modelamiento Electromagnético');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL001138512','COL0011385','Procesamiento de seńales de fenómenos electromagnéticos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL001138513','COL0011385','Protección contra sobretensiones');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL001138514','COL0011385','Redes de Sensores WSN');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL001138515','COL0011385','Sistemas Distribuidos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL001138516','COL0011385','Sistemas Inteligentes de Transporte');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL001138517','COL0011385','Sistemas de Puesta a Tierra');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL001138518','COL0011385','Vehículos eléctricos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00610461','COL0061046','FISIOLOGIA DE LA PAPA');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00610462','COL0061046','MEJORAMIENTO GENETICO DE PAPA');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00610463','COL0061046','PRODUCCION E INVESTIGACION DE SEMILLA DE PAPA');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00610464','COL0061046','RECURSOS GENETICOS DE PAPA');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00610465','COL0061046','SANIDAD VEGETAL DE PAPA');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00117791','COL0011779','COSTEO DE PROYECTOS DE INVESTIGACION Y DESARROLLO EN BIOTECNOLOGIA');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00117792','COL0011779','GENERACION DE EMPRESAS BIOTECNOLOGICAS');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00117793','COL0011779','Gestión de la innovación');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00117794','COL0011779','Inteligencia competitiva, vigilancia y prospectiva tecnológica');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00117795','COL0011779','Planeación estratégica de ciencia y tecnología');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00264591','COL0026459','Control de sistemas no lineales');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00094761','COL0009476','Biomecánica computacional');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00094762','COL0009476','Biotecnología');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00094763','COL0009476','Dinámica de fluidos computacional');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00094764','COL0009476','Elementos Finitos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00094765','COL0009476','Elementos sin malla');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00094766','COL0009476','Investigación en Ciencias de la Salud');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00094767','COL0009476','Modelado de Materiales y fenómenos físicos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00094768','COL0009476','Métodos Numéricos en Ingeniería');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00094769','COL0009476','Simulación y Modelamiento en procesos térmicos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL000947610','COL0009476','Visualización Biomédica');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01481751','COL0148175','Tecnologías de la Información y Comunicación aplicadas a la Educación');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01547711','COL0154771','Competencias del administrador');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01547712','COL0154771','Mejores prácticas empresariales');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01547713','COL0154771','Negocios Internacionales');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00099121','COL0009912','Conflictos socio-ambientales y desigualdades étnicas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00099122','COL0009912','Economía Ecológica y Sustentabilidad');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00099123','COL0009912','Gestión comunitaria y local en agua y saneamiento');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00099124','COL0009912','Gobernanza, ambiente y equidad');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00099125','COL0009912','Género y agua');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00580961','COL0058096','Estímulos biofísicos en Ingeniería de Tejidos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00580962','COL0058096','Mecanobiología computacional');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00580963','COL0058096','Mecanobiología del desarrollo y comportamiento de tejidos blandos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00580964','COL0058096','Mecanobiología del desarrollo y comportamiento de tejidos duros');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00580965','COL0058096','Mecánica celular');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00251481','COL0025148','Inteligencia competitiva y de mercados sectorial y territorial.');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00251482','COL0025148','Encadenamiento Industrial');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00251483','COL0025148','Gestión Ambiental');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00251484','COL0025148','Hidrocarburos y Desarrollo Regional');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00251485','COL0025148','Plan de Ciencia y Tecnología');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00292451','COL0029245','Epidemiológica');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01614891','COL0161489','Computación aplicada');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01614892','COL0161489','Redes y sistemas de Telecomunicaciones');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01614893','COL0161489','Servicios de Telecomunicaciones');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01614894','COL0161489','Sistemas inteligentes');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00656891','COL0065689','Calidad e Innovación en los servicios de salud');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00656892','COL0065689','Innovación Y Multiculturalidad hacia el desarrollo Sostenible');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00656893','COL0065689','Salud y Comunidad');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00692131','COL0069213','Aceptación, uso e integración de tecnología en procesos educativos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00692132','COL0069213','Desarrollo autónomo de actividades en procesos educativos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00692133','COL0069213','Evaluación del impacto y la integración de tecnologías en el ámbito de la educación, medio ambiente, transporte, seguridad o salud');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00692134','COL0069213','Formación en Ingeniería a través de la tecnología');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00692135','COL0069213','Gestión del conocimiento para la formulación de políticas públicas educativas');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00692136','COL0069213','Innovación con el uso de tecnología para la solución de problemas locales y nacionales');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00692137','COL0069213','Tecnología para el desarrollo de competencias en educación');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00380661','COL0038066','Agroplasticultura');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00380662','COL0038066','Control climático de invernaderos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00380663','COL0038066','I + D para la exportación agrícola');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00380664','COL0038066','Ventilación natural en invernaderos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00345951','COL0034595','BIENES AMBIENTALES');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00345952','COL0034595','Desarrollo territorial');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00345953','COL0034595','Gestión ambiental rural');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00345954','COL0034595','Gestión integral del recurso hídrico');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00345955','COL0034595','Gestión integral en el manejo de residuos líquidos y sólidos');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00345956','COL0034595','Métodos de evaluación ambiental');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00345957','COL0034595','Producción limpia');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00345958','COL0034595','SERVICIOS AMBIENTALES');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00596381','COL0059638','Economía de la defensa y del conflicto');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00596382','COL0059638','Gestión Ambiental');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL00596383','COL0059638','Política Económica');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01477681','COL0147768','Didáctica de la ingeniería e ingeniería didáctica en la enseńanza de la ingeniería');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01477682','COL0147768','Diseńo curricular para el desarrollo de competencias en STEM+B');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01477683','COL0147768','Educación STEM+B para todos:');
REPLACE INTO `uapa_db`.`GP_DATOS_LINEAS`(`CODGP_LINEA`,`CODGP`,`Nombre_Línea_Inv`) VALUES('COL01477684','COL0147768','Evaluación de aprendizajes STEM');
