REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00057621','COL0005762','Energía');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00057622','COL0005762','Producción y distribución de energía eléctrica');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00057623','COL0005762','Productos y servicios para la defensa y protección del medio ambiente, incluyendo el desarrollo sostenible.');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00108891','COL0010889','Captación, tratamiento y distribución de agua, limpieza urbana, aguas residuales y actividades conexas');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00108892','COL0010889','Fabricación de catalizadores');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00108893','COL0010889','Fabricación de estructuras metálicas, calderería pesada, tanques, reservatorios y otros productos de metal, exclusive máquinas y equipos');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00108894','COL0010889','Fabricación de otros productos químicos');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00108895','COL0010889','Fabricación de productos de goma y plásticos');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00108896','COL0010889','Fabricación de productos químicos orgánicos');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00108897','COL0010889','Fabricación de resinas y elastómeros');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00108898','COL0010889','Otro');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00108899','COL0010889','Productos y procesos biotecnológicos vinculados a la agricultura');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL001088910','COL0010889','Productos y servicios para la defensa y protección del medio ambiente, incluyendo el desarrollo sostenible.');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00008821','COL0000882','Captación, tratamiento y distribución de agua, limpieza urbana, aguas residuales y actividades conexas');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00008822','COL0000882','Productos y procesos biotecnológicos');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00211391','COL0021139','Desarrollo de programas software');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00211392','COL0021139','Educación');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00211393','COL0021139','Fabricación de máquinas con componentes de mecánica de precisión');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00211394','COL0021139','Fabricación de otros aparatos e instrumentos de medida, test y control, exceto equipos para control de procesos industriales');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00211395','COL0021139','Fabricación de productos cerámicos');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00105661','COL0010566','Asesoramiento o consultoría jurídica, contábil, de opinión pública y en la gestión de empresas');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00105662','COL0010566','Calidad y Productividad');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00105663','COL0010566','Captación, tratamiento y distribución de agua, limpieza urbana, aguas residuales y actividades conexas');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00105664','COL0010566','Producción vegetal');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00105665','COL0010566','Productos y procesos biotecnológicos vinculados a la agricultura');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00105666','COL0010566','Productos y servicios para la defensa y protección del medio ambiente, incluyendo el desarrollo sostenible.');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00077581','COL0007758','Educación');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00077582','COL0007758','Otras actividades de asesoramiento y consultoría a las empresas');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00024391','COL0002439','Desarrollo de nuevos materiales');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00024392','COL0002439','Fabricación de máquinas, aparatos y equipos de sistemas electrónicos dedicados a la automación industrial y control del proceso productivo');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00024393','COL0002439','Fabricación de máquinas, aparatos y materialies eléctricos');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00144581','COL0014458','Asesoramiento y consultoría en arquitectura e ingeniería');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00144582','COL0014458','Desarrollo de nuevos materiales');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00144583','COL0014458','Desarrollo de programas software');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00144584','COL0014458','Educación');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00144585','COL0014458','Producción y distribución de energía eléctrica');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00113851','COL0011385','Asesoramiento y consultoría en arquitectura e ingeniería');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00113852','COL0011385','Construcción civil');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00113853','COL0011385','Desarrollo de nuevos materiales');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00113854','COL0011385','Desarrollo de programas software');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00113855','COL0011385','Ensayos de materiales y productos análisis de calidad');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00113856','COL0011385','Fabricación de máquinas, aparatos y materialies eléctricos');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00113857','COL0011385','Fabricación de material electrónico básico');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00113858','COL0011385','Fabricación de otros aparatos e instrumentos de medida, test y control, exceto equipos para control de procesos industriales');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00113859','COL0011385','Producción y distribución de energía eléctrica');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00610461','COL0061046','Producción vegetal');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00117791','COL0011779','Otras actividades de asesoramiento y consultoría a las empresas');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00117792','COL0011779','Productos y procesos biotecnológicos vinculados a la agricultura');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00117793','COL0011779','Productos y procesos biotecnológicos vinculados a la salud humana o de los animales');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00099121','COL0009912','Desarrollo rural');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00099122','COL0009912','Desarrollo Urbano');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00345951','COL0034595','Actividades de asesoramiento y consultoría a las empresas');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00345952','COL0034595','Desarrollo Urbano');
REPLACE INTO `uapa_db`.`GP_DATOS_SECTORES`(`CODGP_SECTOR`,`CODGP`,`Sector_de_Aplicación`) VALUES('COL00345953','COL0034595','Productos y servicios para la defensa y protección del medio ambiente, incluyendo el desarrollo sostenible.');
